language: node_js
node_js:
  - lts/*
install:
  - yarn install # npm ci
cache:
  directories:
    - node_modules
  yarn: true
script:
  - yarn deploy-gh # npm run docs:build
deploy:
  provider: pages
  cleanup: true
  local_dir: public
  token: $GH_TOKEN # 在 GitHub 中生成，用于允许 Travis 向你的仓库推送代码。在 Travis 的项目设置页面进行配置，设置为 secure variable
  target_branch: gh-pages
  keep_history: true
  on:
    branch: master