language: node_js
node_js:
- lts/*
install:
- yarn install
cache:
  directories:
  - node_modules
  yarn: true
script:
- yarn deploy-gh
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    branch: master
env:
  global:
    secure: O4w6qEuh9hSbZldjHSy0MA88bk2ZcM+DFvF8ssx3LW8pk31Z+hw57FSbRxxEqgeQirPSaVtE+K07KunyOf4XXWVyuT+MeOfEh2xU1KgOEfAxJKuUgSYhoy3gR8n5xR+MTCi6+gdB8za60xFiiRG8xNuETwL7DQE9JmWDGaItnFDhilZFTtCHvALiaxQw6f7BWcehHXaNkrK2acZB9xLzCHf+ZKBH4Eq85+LpUkbzqUU1+awF2wHAhU5R/e6CP4yZC/CO+B7hdLUhye8IEsqgwqjN9KGqqE/G98BI7ZsbaibLQPjD1Se+Th6ld0blTsI4p1zO5geY4CZB4cR93wXmA8DkcDmo80wHXk+Fo6owtjlS7YCLendLO/PRQSn2SEczqBtOXy/p1nhJxPbWii/KNQJ6nOseSWq6xO+oY+zhwr5BSvsGBw9MPL+hbfwwthUAy3rbTvLOliT7j/FvJcjbsvwiIHzsuRoh3aeEfg0F6p4GuVO5vUFlEzJ32GeC53Nf/SSSDNdglh02aqX0HirQte4ZVzXfXV+q2UsUfqWyoqIecRR0l4ULRMnURMIKsLmJ8YzFMk384PuT1wQHeWv9uRDLRuv9jnN7eliRANwgBWOu3Apwf9nYXNdULxWGBZ9fa47QyRSc7aqXKvX+Nj9yCgBou2W1zNpMuxB/63yyNAM=
